# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TPJsBridge' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TPJsBridge
  pod 'TPJsBridge’, :path => ‘../’
end
